name = "${PROJECT_NAME}"
main = "worker.js"
compatibility_date = "2023-08-23"

[vars]
TARGET_DOMAIN = "${TARGET_DOMAIN}"
SERVE_DOMAIN = "${SERVE_DOMAIN}"
GISCUS_REPO = "${GISCUS_REPO}"
GISCUS_REPO_ID = "${GISCUS_REPO_ID}"
GISCUS_CATEGORY = "${GISCUS_CATEGORY}"
GISCUS_CATEGORY_ID = "${GISCUS_CATEGORY_ID}"