name: Deploy Worker

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Specify project name
        run: |
          sed -i 's\${PROJECT_NAME}\${{ github.repository_owner }}\g' cloudflare-worker/wrangler.toml
          sed -i 's\${TARGET_DOMAIN}\${{ vars.TARGET_DOMAIN }}\g' cloudflare-worker/wrangler.toml
          sed -i 's\${SERVE_DOMAIN}\${{ vars.SERVE_DOMAIN }}\g' cloudflare-worker/wrangler.toml
          sed -i 's\${GISCUS_REPO}\${{ vars.GISCUS_REPO }}\g' cloudflare-worker/wrangler.toml
          sed -i 's\${GISCUS_REPO_ID}\${{ vars.GISCUS_REPO_ID }}\g' cloudflare-worker/wrangler.toml
          sed -i 's\${GISCUS_CATEGORY}\${{ vars.GISCUS_CATEGORY }}\g' cloudflare-worker/wrangler.toml
          sed -i 's\${GISCUS_CATEGORY_ID}\${{ vars.GISCUS_CATEGORY_ID }}\g' cloudflare-worker/wrangler.toml
          
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: "cloudflare-worker"
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
